/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nexmo.starter;

import org.junit.Ignore;
import org.junit.Test;

public class AppTest {
    @Test
    @Ignore
    public void testAppHasAGreeting() {
        // Empty Test
    }
}
